//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boldly.Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boldly.Domain.Localization.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address.
        /// </summary>
        public static string EmailAddressWithArticle {
            get {
                return ResourceManager.GetString("EmailAddressWithArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email.
        /// </summary>
        public static string EmailWithArticle {
            get {
                return ResourceManager.GetString("EmailWithArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name.
        /// </summary>
        public static string NameWithArticle {
            get {
                return ResourceManager.GetString("NameWithArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical name.
        /// </summary>
        public static string TechnicalName {
            get {
                return ResourceManager.GetString("TechnicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The technical name.
        /// </summary>
        public static string TechnicalNameWithArticle {
            get {
                return ResourceManager.GetString("TechnicalNameWithArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text.
        /// </summary>
        public static string TextWithArticle {
            get {
                return ResourceManager.GetString("TextWithArticle", resourceCulture);
            }
        }
    }
}
