
name: Continuous Integration

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_call:
  

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Build
        shell: pwsh
        run: ./build.ps1
      
      - name: Test
        shell: pwsh
        run: ./test.ps1